// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqqlrliakttqsbalvuyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcWxybGlha3R0cXNiYWx2dXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjI2NTQsImV4cCI6MjA2MjkzODY1NH0.powX3nV61-Np-2_DKioUIEqG__OHx0BtpK7TFp6ri5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);